USE [master]
GO

/****** Object:  Database [Education2020]    Script Date: 6/8/2021 11:08:25 AM ******/
CREATE DATABASE [Education2020]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Education2020', FILENAME = N'D:\SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Education2020.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Education2020_log', FILENAME = N'D:\SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Education2020_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Education2020].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Education2020] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Education2020] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Education2020] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Education2020] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Education2020] SET ARITHABORT OFF 
GO

ALTER DATABASE [Education2020] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Education2020] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Education2020] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Education2020] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Education2020] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Education2020] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Education2020] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Education2020] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Education2020] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Education2020] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Education2020] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Education2020] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Education2020] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Education2020] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Education2020] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Education2020] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Education2020] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Education2020] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Education2020] SET  MULTI_USER 
GO

ALTER DATABASE [Education2020] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Education2020] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Education2020] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Education2020] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Education2020] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Education2020] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Education2020] SET  READ_WRITE 
GO


